import type { Artist } from "./artist.js";
import type { GenreId } from "./genre.js";
import type { Pager } from "./common.js";
import type { Track } from "./track.js";
type AlbumType = "compilation" | string;
type Label = {
    id: number;
    name: string;
} | string;
type AlbumCustomWave = {
    title: string;
    animationUrl: string;
    header: string;
};
export type AlbumVolume = Track[];
export type Album = {
    id: number;
    title: string;
    type: AlbumType;
    metaType: string;
    version: string;
    year?: number;
    releaseDate: string;
    coverUri: string;
    ogImage: string;
    genre: GenreId;
    metaTagId?: string;
    trackCount: number;
    recent?: boolean;
    veryImportant: boolean;
    artists: Artist[];
    labels?: Label[];
    available: boolean;
    availableForPremiumUsers: boolean;
    disclaimers: string[];
    availableForOptions: string[];
    availableForMobile: boolean;
    availablePartially: boolean;
    bests: number[];
    duplicates?: Album[];
    customWave?: AlbumCustomWave;
    sortOrder?: string;
    volumes?: AlbumVolume[];
    pager?: Pager;
};
export type AlbumWithTracks = Required<Pick<Album, "volumes">> & Album;
export type AlbumSimilarEntities = {
    albums: Album[];
    artists: import("./artist.js").Artist[];
    tracks: import("./track.js").Track[];
};
export type AlbumTrailer = {
    title: string;
    cover: string;
    url: string;
    provider?: string;
    providerVideoId?: string;
};
export type AlbumId = number;
export type AlbumUrl = string;
export {};
